apiVersion: v1
kind: Service
metadata:
  labels:
    app: mssql
  name: mssql
spec:
  ports:
  - name: mssql-tcp
    port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: mssql
    deploymentconfig: mssql
  sessionAffinity: None
  type: ClusterIP
