apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: mssql-init
  name: mssql-init
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: mssql-init:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/gwachter77/mssql-okd.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: mssql-init/Dockerfile
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
